import React from 'react';

type DefaultRendererArgs = [string | React.FunctionComponent, Record<string, any>, React.ReactNode];

const defaultRenderer = (...args: DefaultRendererArgs) => React.createElement(...args);

// https://github.com/cure53/DOMPurify/blob/main/src/tags.js#L3-L121
const htmlTags = [
  'a',
  'abbr',
  'acronym',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'bdi',
  'bdo',
  'big',
  'blink',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'center',
  'cite',
  'code',
  'col',
  'colgroup',
  'content',
  'data',
  'datalist',
  'dd',
  'decorator',
  'del',
  'details',
  'dfn',
  'dialog',
  'dir',
  'div',
  'dl',
  'dt',
  'element',
  'em',
  'fieldset',
  'figcaption',
  'figure',
  'font',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'img',
  'input',
  'ins',
  'kbd',
  'label',
  'legend',
  'li',
  'main',
  'map',
  'mark',
  'marquee',
  'menu',
  'menuitem',
  'meter',
  'nav',
  'nobr',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'section',
  'select',
  'shadow',
  'small',
  'source',
  'spacer',
  'span',
  'strike',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'template',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'tr',
  'track',
  'tt',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
] as const;

export type AllowedHtmlTagsMap = Record<typeof htmlTags[number], typeof defaultRenderer>;

// We don't want to use any block-list approach. because there is always a chance that we
// either forget something, or that someone will find a way to bypass our block-list (eg. by using unicode).
// Instead, we use an allowed-list approach.
export const allowedHtmlTags: AllowedHtmlTagsMap = htmlTags.reduce(
  (allowedTags, htmlTag: string) => ({
    ...allowedTags,
    [htmlTag]: defaultRenderer,
  }),
  {} as AllowedHtmlTagsMap
);
